baseURL = 'https://mthood-ski-patrol.netlify.app/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = 'PaperMod'
[params]
  profileMode = { enabled = false }
  homeInfoParams = false


[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Blog"
    url = "/blog/"
    weight = 2
  [[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 3
  [[menu.main]]
    name = "Payment"
    url = "/payment/"
    weight = 4